"""Interview prep briefs — `make brief COMPANY=x`.

Built from enrichment already paid for, so it costs nothing extra: the founders
and their backgrounds, the funding line, the job description, and the CV entries
that match the role.

The questions are the useful part. Eric's profile generates the same handful
every time — why leave the Jets, why not stay in sports, why this industry, what
does a data person want with a GTM seat — and having answered them once in
writing is worth more than any amount of company research. Those live in
data/answers.md so they get reused and sharpened rather than improvised at 11pm.
"""

from __future__ import annotations

from pathlib import Path

from . import cv
from .models import Entry

# Where per-company artifacts live. Moved here from outreach.py when the
# dossier flow was retired (2026-08-06) — briefs and `make today`'s artifact
# scan still need the directory and the slug rule.
ROOT = Path(__file__).resolve().parent.parent
APPLICATIONS = ROOT / "applications"


def slug(name: str) -> str:
    import re
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-") or "unknown"

ROOT = Path(__file__).resolve().parent.parent
ANSWERS_PATH = ROOT / "data" / "answers.md"

# The questions Eric's specific profile invites. Not generic interview prep —
# each of these is generated by something concrete on his CV.
PROFILE_QUESTIONS = [
    (
        "Why are you leaving the Jets?",
        "You will get this every single time. The honest answer is the strong one: "
        "the Jets work was analysis feeding someone else's decision, and you want to "
        "own the outcome. Do not disparage the role — you helped take special teams "
        "from 24th to 1st, and that only lands if you clearly valued it.",
    ),
    (
        "You're a data person. Why do you want a GTM/ops/founding seat?",
        "The spec's own framing: Python/R/SQL are credibility and a tiebreaker, never "
        "the job. Point at the band — you ran growth, bookings, merch and brand to "
        "profitability — and at Foxino, where you owned US go-to-market. The data "
        "background is why you'll be sharper in the room, not what you'd be doing.",
    ),
    (
        "Why this industry?",
        "Have the specific thread ready. Generic enthusiasm reads as spray-and-pray, "
        "and at a seed company the founder is explicitly filtering for people who "
        "chose them.",
    ),
    (
        "What would you own in the first 90 days?",
        "Answer with something concrete from their actual job description, not a "
        "framework. At this stage they want to hear you've already started thinking "
        "like an operator on their specific problem.",
    ),
    (
        "You've never done this exact job. Why you?",
        "Do not apologise for the gap. The 0-to-1 pattern is the argument: band from "
        "zero to profitable, US GTM at Foxino, an NLP pipeline that secured grant "
        "funding. You have repeatedly built things without a playbook.",
    ),
]


def _founder_lines(entry: Entry) -> list[str]:
    if not entry.founders:
        return ["- No founder data on file. Look them up before the call."]
    out = []
    for f in entry.founders:
        bits = [f"**{f.get('name', '(unknown)')}**"]
        if f.get("title"):
            bits.append(f"— {f['title']}")
        out.append("- " + " ".join(bits))
        if f.get("linkedin"):
            out.append(f"  - {f['linkedin']}")
    return out


def render(entry: Entry, description: str = "") -> str:
    tags = cv.tags_for_role(entry.title, description)
    matches = cv.best_entries(tags, limit=3)

    lines = [
        f"# Interview brief — {entry.company}",
        "",
        f"**Role:** {entry.title}  ",
        f"**Posting:** {entry.url}  ",
        f"**Stage / funding:** {entry.stage or '—'} · {entry.funding or '—'}  ",
        f"**Location:** {entry.location or '—'}  ",
        f"**Score:** {entry.score if entry.score is not None else '—'}  ",
        "",
        f"**Why this scored the way it did:** {entry.why}",
        "",
        "## Who you'll be talking to",
        "",
        *_founder_lines(entry),
        "",
    ]

    if entry.warm_path:
        lines += ["## Warm path", "", entry.warm_path, ""]

    lines += ["## Questions you will be asked", ""]
    for q, guidance in PROFILE_QUESTIONS:
        lines += [f"### {q}", "", guidance, "", "_Your answer:_", "", "", ]

    lines += [
        "## Three questions to ask them",
        "",
        "Ask things that only apply to a company at this stage. Avoid anything",
        "answerable from the website.",
        "",
        "1. What does this role own in six months that nobody owns today?",
        "2. What's the thing you believe about this market that most people building",
        "   here get wrong?",
        "3. Where does the current go-to-market break first if it works?",
        "",
        "## Your strongest material for this conversation",
        "",
    ]

    if matches:
        for m in matches:
            lines.append(f"**{m.role} · {m.org}**")
            for b in m.bullets[:3]:
                lines.append(f"- {b}")
            lines.append("")
    else:
        lines += ["(no tag match — lead with the Jets and the band)", ""]

    lines.append(f"_Matched on: {', '.join(tags) or 'nothing specific'}_")
    lines.append("")

    if ANSWERS_PATH.exists():
        lines += [
            "## Reusable answers",
            "",
            f"See `{ANSWERS_PATH.relative_to(ROOT)}` — sharpen those rather than",
            "rewriting from scratch each time.",
            "",
        ]

    if description:
        lines += ["## The posting", "", "```", description[:5000], "```", ""]

    return "\n".join(lines)


def generate(entry: Entry, description: str = "") -> Path:
    d = APPLICATIONS / slug(entry.company)
    d.mkdir(parents=True, exist_ok=True)
    path = d / "brief.md"
    path.write_text(render(entry, description), encoding="utf-8")
    return path
